name:                stl-parser
version:             0.1.0.0
#synopsis:
#description:
homepage:            https://github.com/githubuser/stl-parser#readme
license:             BSD3
author:              Author name here
maintainer:          example@example.com
copyright:           2017 Author name here
category:            Web
extra-source-files:
- README.md

dependencies:
  - base >= 4.7 && < 5
  - megaparsec >= 6.0.0 && < 7.0.0

executables:
  stl-parser:
    source-dirs:      src
    main:             Main.hs
